### ISSUE TITLE
setup tutorial

### ISSUE THREAD

**Issue by Semetra22** [yunnanpl/esp32_python_eq3#12]
Looks really promising and is exactly what I'm looking for! 
Unfortunately, I have no real experience with compiling the code for an ESP. I have customized the secret_cfg, but have no starting point how to compile the whole thing and flash it on the device. 
A little tutorial would really help me out! 

Great work, thanks a lot!

(By the way, very clean and well commented code!)

**Comment by yunnanpl** [comment]
I added the Installation part to the main page.
The first upload of the files is tricky, but then you can use the "over the air" updater.

I hope it will be of help !

**Comment by Semetra22** [comment]
Thanks Dr. JJ
You're awesome!
