### ISSUE TITLE
ESP32 BLE LONG RANGE(>300m)

### ISSUE THREAD

**Issue by Saiuday9787** [yunnanpl/esp32_python_eq3#30]
Hiii, I am trying for LONG RANGE BLE (>300meters) using ESP32 C3 mini-1.

I tried esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P21);  at server side and client side, still i am able to get Line of site upto 100meters and able to tx via one floor concrete slab. still my requirement is not satisfied, 
Can you suggest on how to achieve above 300meters range.

**Comment by yunnanpl** [comment]
Duplicate.
See https://github.com/yunnanpl/esp32_python_eq3/issues/29
