### ISSUE TITLE
Missing setup instructions

### ISSUE THREAD

**Issue by tofferlicious** [yunnanpl/esp32_python_eq3#7]
Thank you very much for this project. Unfortunately I could not get it running properly so far.

I configured everything to my best knowledge inside the secret_cfg.py.
But somehow I am still getting this exception and I cannot further analyze it, due to the "simple2.mpy" binary:

> Traceback (most recent call last):
>   File "main.py", line 888, in <module>
>   File "main.py", line 860, in fmqtt_recover
>   File "simple2.py", line 70, in connect
> MQTTException: 25

Am I still missing something? I got Home Assistant running with the add-on Mosquitto broker and I am using the credentials from it.
If I remember correctly, this was working fine with the esp32_mqtt_eq3 project.

**Comment by yunnanpl** [comment]
Dear tofferlicious,
I assume there is an issue with MQTT server. I do confess I use MQTT without password on my local isolated network.
...
and I do confess, I have not tested it with password.

So, in the line 886 in boot.py, it is:
`mqtth = umqtt.MQTTClient(config2['mqtt_usr'], config2['mqtt_srv'], user=config2['mqtt_usr'], password=config2['mqtt_usr'], port=1883)`
and it should be:
`mqtth = umqtt.MQTTClient(config2['mqtt_usr'], config2['mqtt_srv'], user=config2['mqtt_usr'], password=config2['mqtt_pass'], port=1883)`
(in short, I used the user variable for the password...).

Let me know if it works.

PS. I just updated micropython to 1.17 stable and it seems more responsive... but the tests will show.

PS2. This project is quite far from esp32_mqtt_eq3... it is based on micropython, and rewritten from scratch. Still, I tried to keep the previous syntax, but still improving some things (which in real life means, breaking some other things ;D).

**Comment by tofferlicious** [comment]
Hello Dr. JJ,
Thanks, that solved it! Why did not I notice that 😅
I will read more through the code to get a better understanding.
It is defintely more comfortable to debug than the esp32_mqtt_eq3 project.

In the end I would like to integrate my eq3 into home-assistant.

**Comment by yunnanpl** [comment]
Dear tofferlicious,
I have not noticed it either, as I do not use password with mqtt.

Unfortunately, as it was "corona"-project, I do not have so much time as I had before.
I do use it with home-assistant, so it surely works. The configuration is the same as it was for esp32_mqtt_eq3,
Still, I have not finished the "auto mqtt home assistant" configuration for the climate components.

Yes, debuginng is quite nice, explicitly with webrepl console (if you have issues with it, try to open the console in incognito mode).
There is still a lot work to do ;) but the stability is much better (the esp32 are rebooting themselves if webpage, mqtt or anything fails).

PS. I find the story with ble messages triggering an interrupt slightly confusing... so even if I tried to comment the code for myself, it might be challenging to read it :D

**Comment by yunnanpl** [comment]
So, as discusses, the code is improved significantly. Much faster, and even more stable.
I also added the home assistant autodiscovery, which makes it really fun to use (no climate and mqtt manual configuration...).
Now all automations are easy and simple, and everything is working even on weak BLE connections !

Still no "modes" added, but the code is ready for it, so it will be added soon (at least the auto, boost and manual).
The on, off, away modes can be easily "simulated" with temperature setting.
Furthermore, for me the offset is important, so I will add it both on the EQ3 part, and an additional offset on ESP32 (as my feeling is that the EQ3 offset does not work so well).

**Comment by yunnanpl** [comment]
So, the newest version is really quite stable and robust, even for EQ3 thermostats with RSSI worse than -90.
Autodiscovery works very well.
Instructions and change log added to separate files in GitHub for readibility.
