### ISSUE TITLE
Startup Issues

### ISSUE THREAD

**Issue by Odyssey666** [yunnanpl/esp32_python_eq3#8]
Hi,
first of all, thank you for this project. 
Though I tried out a lot of different settings, I don't get it to run properly.
What works: accessing the Website, as well as connecting to the ESP32 via WEBREPL. If I click 'list of devices' I get a list of BLE devices in range. If I click then 'add' in front of the row containing a EQ-3 BT thermostate, it replies xy:xy:xy:xy whitelisted. But the 'List of contacted devices' remains always empty. I also don't see any publishings to the MQTT server neither do I get any response if I publish anything on the required topics. maybe it is a configuration issue. My secret-cfg.py contains:
    config2['mqtt_srv'] = '192.168.178.26'
    config2['mqtt_usr'] = ''
    config2['mqtt_pass'] = ''
I don't use a user and a password to access the MQTT broker.
The valves work fine with esp32_mqtt_eq3, so I don't think it is a firmware issue.
Some help would be nice, but I know that you have don't muchg time.

**Comment by yunnanpl** [comment]
So, yes, the "Add" button is just a trick, it does not work yet (it will be a "whitelist" for the thermostates).
To get some status from the thermostat, send following mqtt at your mqtt server.
Here a shell example:
`
/usr/bin/mosquitto_pub -h mqtt.server.ip
-t /hass/climate/climate_1/radin/trv
-m "00:xxxxxxxx manual"
-I "eq3"
`
So, the topic is the topic you configured in the mqtt for the esp32. It is similar to previous versions and to tasmota.
Then message is the mac address and the command (as previously, manuall gets the info).

Equally the command for changing the temp is:
`
00:xxxxxxxx settemp 23.0
`

Then you will get a respective response on the defined topic, like here:
`
/hass/climate/climate_23/radout/status
{
    "trv": "00:xxxxxxx",
    "temp": "21.0",
    "mode": "manual"
}
`
Parsing from the eq3_mqtt should work here too.

EDIT: The "Add" button will remove the need to send "manual" messages to the esp32, as the whitelisted eq3s will be queried automatically and the mqtt will be published. This will take the load from the server and home assistant.

**Comment by Odyssey666** [comment]
Thx for your reply. Ok, I think I understand my problem now. I thought that you implemented more or less the same commands like esp32_mqtt_eq3. Thus, I published ‚00:xxxxxxxx auto‘ to the ‚…/radin/trv‘ topic without getting any response. After your message I published ‚manual‘ instead of ‚auto‘ and I got the response in the ‚…/radout/status‘ topic and the Thermostate is set to the manual mode. The command ‚settemp‘ works, too. Reading through your code a bit it seems that you only implemented setting the manual mode (not auto or boost) and setting the target temperature.

**Comment by yunnanpl** [comment]
Yes... nothing except "manual" (also for querying the data) and setting is implemented. I am boosting the thermostats also using home assistant.
I know that there is a lot of work before me ;)
but in a meantime, I am having near to no issues with the thermostats.

Sorry if I overpromised, but if something is critical for you, then I will try to set it as a priority (at the moment the priority is the auto-discovery in home assistant using mqtt).

**Comment by Odyssey666** [comment]
I think your major promise was regarding stability. And as far as I can see so far, you achieved that very well ;-)
As I prefer to let the thermostats run in auto mode, I was used to publish ‘auto’ to query the data. But just using ‘settemp’ is also working fine. I prefer the auto mode because then the schedule in the thermostat can act as a fallback if the WiFi or BLE connection is broken or the ESP32 hangs. This prevents me from having to shower in a cold bathroom in the morning ;-)
There might be one critical thing to implement in the future: pairing/authentication to be able to connect with the new firmware of the thermostats. If we need to buy new thermostats they might come with the new firmware on board. And I don’t know if it is possible to downgrade the firmware.
